[server]
enableStaticServing = true

[theme]
base = "dark"
primaryColor = "#1ED760"
backgroundColor = "#121212"
secondaryBackgroundColor = "#333333"
textColor = "#FFFFFF"
linkColor = "#9D9D9D"
borderColor = "#7F7F7F"
showWidgetBorder = false
baseRadius = "0.3rem"
font = "CircularSpotifyText"

[theme.sidebar]
backgroundColor = "#000000"
secondaryBackgroundColor = "#333333"
borderColor = "#696969"


[[theme.fontFaces]]
url = "app/static/CircularSpotifyText-Light.otf"
family = "CircularSpotifyText"
weight = 300

[[theme.fontFaces]]
url = "app/static/CircularSpotifyText-Book.otf"
family = "CircularSpotifyText"
weight = 400

[[theme.fontFaces]]
url = "app/static/CircularSpotifyText-Medium.otf"
family = "CircularSpotifyText"
weight = 500

[[theme.fontFaces]]
url = "app/static/CircularSpotifyText-Bold.otf"
family = "CircularSpotifyText"
weight = 700

[[theme.fontFaces]]
url = "app/static/CircularSpotifyText-Black.otf"
family = "CircularSpotifyText"
weight = 900