"""dropped binary blob columns, introduced url path columns for event image and qr code

Revision ID: 4212f9fd24a2
Revises: e2aa0344bced
Create Date: 2025-05-30 02:39:00.191676

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4212f9fd24a2"
down_revision: Union[str, None] = "e2aa0344bced"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("event_image_url", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "events", sa.Column("qr_code_image_url", sa.String(length=256), nullable=True)
    )
    op.drop_column("events", "event_image")
    op.drop_column("events", "qr_code_image")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column(
            "qr_code_image", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "event_image", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("events", "qr_code_image_url")
    op.drop_column("events", "event_image_url")
    # ### end Alembic commands ###
