"""add event_image and qr_code_image to events

Revision ID: e2aa0344bced
Revises: 4a1b53bc786c
Create Date: 2025-05-29 23:11:47.689367

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2aa0344bced"
down_revision: Union[str, None] = "4a1b53bc786c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("event_image", sa.LargeBinary(), nullable=True))
    op.add_column("events", sa.Column("qr_code_image", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "qr_code_image")
    op.drop_column("events", "event_image")
    # ### end Alembic commands ###
