name: Kanta Face Clustering CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'cluster-faces/src/**'
      - 'cluster-faces/tests/**'
      - 'cluster-faces/pyproject.toml'
      - 'cluster-faces/uv.lock'

jobs:
  test-and-lint:
    name: Test & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Cache virtual environment
        uses: actions/cache@v4
        with:
          path: cluster-faces/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('cluster-faces/uv.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Run Ruff linting
        working-directory: ./cluster-faces
        run: uvx ruff check --fix

      - name: Install the project
        working-directory: ./cluster-faces
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        working-directory: ./cluster-faces
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        run: uv run pytest